export const WORDS = {
  RU: {
    SHOP: "Магазин",
    MAIN: "Главная",
    IN_BASKET: "В корзине:",
    EMPTY: "пусто",
    GO: "Перейти",
    ADD: "Добавить",
    BASKET: "Корзина",
    CLOSE: "Закрыть",
    TOTAL: "Итого",
    PRODUCT: "Товар",
    DELETE: "Удалить",
    PIECE: "шт",
    PLURAL_PRODUCT: {
      one: "товар",
      few: "товара",
      many: "товаров",
    },
    LANG: "ru-RU",
  },
  EN: {
    SHOP: "Shop",
    MAIN: "Main",
    IN_BASKET: "In basket:",
    EMPTY: "empty",
    GO: "Go",
    ADD: "Add",
    BASKET: "Basket",
    CLOSE: "Close",
    TOTAL: "Total",
    PRODUCT: "Product",
    DELETE: "Delete",
    PIECE: "pcs",
    PLURAL_PRODUCT: {
      other: "items",
      one: "item",
    },
    LANG: "en-US",
  },
};
